# Generated by Django 4.2.5 on 2023-09-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.IntegerField(max_length=12)),
                ('user_status', models.IntegerField(choices=[(1, 'administrator'), (2, 'driver'), (3, 'maintenance_person'), (4, 'gas_fueling_person')], default=1)),
            ],
        ),
    ]
